title: 中文SM经典小说
email: victorwsma@gmail.com
description: 高质量中文SM小说集合
baseurl: ""

markdown: kramdown
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-remote-theme

google_analytics: G-HYN8MF0VM4
